// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kztyssmelucohyeyauqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6dHlzc21lbHVjb2h5ZXlhdXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTg1MTksImV4cCI6MjA2NDYzNDUxOX0.7FMy8QjYjWZEOaDsZMXzGX_lWMR5ZwXLADtmIAcgG8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});